package aueb.mcsis.omada7.services.eforia;

public class IpovolhDhlwshsService {
	//DEXETE BOOLEAN OTI UPARXEI LOGARIASMOS
	//KAI BOOLEAN GIA TO XRONIKO DIASTIMA DILOSEWN
	//EKXOREI SE DUO VARIABLE ESODA KAI EXODA
}
