package aueb.mcsis.omada7.services.eforia;

public class TropopoihshDhlwshsService {
	//BOOLEAN TROPOISIS  ENTOS XRONIKOU TRUE 
	//STO FALSE DEN BOREI
	//EISAGWGH ESODWN EXODWN SE VAR KAI DIAXRAFONTAI OI PROIGOUMENES KATAXORISEIS
	//(PERNEI THN TROPOISI APO TON ELEGXO)
}
